### ISSUE TITLE
Re-export mongoose types?

### ISSUE THREAD

**Issue by Powersource** [Edgeryders-Participio/plato-core#1]
When I want to create e.g. an orgMember, I need to create an ObjectId for the organizationId, and then I need to [import mongoose](https://stackoverflow.com/a/8393613). Which is installed by this project but not directly by mine. So would be nice if I could import the needed types from this project instead

**Comment by gustavlrsn** [comment]
I think you should be able to use a string as organizationId directly, and mongoose will cast it to an ObjectId

**Comment by Powersource** [comment]
Ah nice yeah that seems to work! Funny that no one on stackoverflow would mention that
