### ISSUE TITLE
Let people log in using facebook and google

### ISSUE THREAD

**Issue by Powersource** [Edgeryders-Participio/plato-core#7]
For my reference:

Facebook settings https://developers.facebook.com/apps/411826776774574/settings/basic/  
Google settings https://console.cloud.google.com/apis/credentials/consent?project=plato-project

* [x] Make fb work
* [x] "Action Required: Complete Data Use Checkup for Plato Project by July 31, 2021." Link in header on fb settings
* [x] Add redirects in dreams to policies, so we can link to those instead of directly to iubenda (google complains)
* [ ] Wait to get verified by google
* [ ] Make google work

**Comment by Powersource** [comment]
![image](https://user-images.githubusercontent.com/1427063/107938953-5ce8e600-6f86-11eb-8300-21254795a3a0.png)

nice

**Comment by skoteskote** [comment]
Brilliant! Is it possible to add google too if it's easy?

**Comment by Powersource** [comment]
Ah sure I'll look into it

**Comment by Powersource** [comment]
As mentioned in chat: got google to work for me, but if we want users to be able to sign up then they require us to have a privacy policy

**Comment by Powersource** [comment]
Switched facebook from dev to live mode. Can someone other than me try logging in using fb?

**Comment by skoteskote** [comment]
<img width="535" alt="Screenshot 2021-06-01 at 13 32 11" src="https://user-images.githubusercontent.com/11414586/120316629-ecb86300-c2dd-11eb-8b71-edf09cfc8d83.png">
Tried now but got this

**Comment by Powersource** [comment]
Applied to be verified by google and got this back

> The Trust and Safety team has received your form. They will reach out to you via your contact email if needed. The review process can take up to 4-6 weeks. Expect the first email from our Trust and Safety team within 3-5 days. Your last approved consent screen is still in use.

It's a bit unclear if this is just because I added an image. And if they'll let us log in in the meantime just without the image lol

**Comment by Powersource** [comment]
![image](https://user-images.githubusercontent.com/1427063/120317791-5d13b400-c2df-11eb-921a-640f8efef694.png)

And this is lovely. They needed me to link to our privacy policy. So I put https://www.iubenda.com/privacy-policy/58637640 , but then google assumed that was our server and requires us to verify it's ours. I guess I'll have to add a page on dreams.wtf that just redirects you to the policy, just so I can give that link to google lol...

**Comment by skoteskote** [comment]
Omg, that's so annoying. Weird as iubenda is super common for these things.

**Comment by Powersource** [comment]
@skoteskote ok so I've checked a few more boxes on fb, could you try again now?

**Comment by Powersource** [comment]
Also fb says "Action Required: Complete Data Use Checkup for Plato Project by July 31, 2021." so that's fun

**Comment by skoteskote** [comment]
Yay it worked! Or, I got to the last screenshot, but I don't have access to my FB email so I can't check I actually got the mail.
<img width="541" alt="Screenshot 2021-06-01 at 14 09 49" src="https://user-images.githubusercontent.com/11414586/120321051-23dd4300-c2e3-11eb-910d-a11ec0823bef.png">
<img width="842" alt="Screenshot 2021-06-01 at 14 10 22" src="https://user-images.githubusercontent.com/11414586/120321070-263f9d00-c2e3-11eb-8d1f-de00bd0d8aa4.png">
<img width="525" alt="Screenshot 2021-06-01 at 14 11 35" src="https://user-images.githubusercontent.com/11414586/120321291-6ef75600-c2e3-11eb-9eae-5141e5e7fdb5.png">

**Comment by Powersource** [comment]
Added the redirects https://github.com/Edgeryders-Participio/multi-dreams/pull/266

**Comment by Powersource** [comment]
I've now verified both platoproject.org and dreams.wtf, and replied to their email, so now I think we just need to wait. [From this documentation](https://support.google.com/cloud/answer/7454865) it sounds like we might be able to let users log in with google for now anyway, but there would be a really bad warning screen, so I think it's best to just wait.

**Comment by Powersource** [comment]
Moved the policies into iframes on our page, since it seemed google were annoyed that they were on a page hosted by someone else. I've contacted them to start the approval process again

**Comment by Powersource** [comment]
Both google and fb seems to work now!
